### ISSUE TITLE
An employee should be able to retreive all employees from current organization

### ISSUE THREAD

**Issue by bitspook** [sosinc/sos-app#76]
We need to store current-organization in session, which we'll then pass to hasura in authentication webhook. To achieve this:
1. In `me` query, send user's first organization as `currentOrganization`
2. Create a mutation in sidecar named `setCurrentOrganization`, which is called every time user changes their organization. Store this organization-id in session.
3. Add row-selection filter in hasura for employees based on `X-Hasura-Organization-Id`. Make sure to send `X-Hasura-Organization-Id` in authentication webhook

**Comment by bitspook** [comment]
@jkhabra Can we close this issue? I think this is already done.

**Comment by jkhabra** [comment]
yes  i think so
